In [1]:
import numpy as np

1.Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [2]:
np.random.rand(25)

array([0.27628152, 0.18075336, 0.86481685, 0.7672021 , 0.79818603,
       0.26865812, 0.52282983, 0.54205056, 0.65699158, 0.15631513,
       0.97609684, 0.66551928, 0.84002863, 0.65043866, 0.10143217,
       0.31758527, 0.00611303, 0.46110225, 0.83528512, 0.67856429,
       0.55820522, 0.30571397, 0.15131465, 0.47679419, 0.10477986])

2.Create an array of 20 linearly spaced points between 0 and 1

In [3]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

3.Declare a numpy array of values from 1 to 100 and make it into a 10*10 matrix. 

In [4]:
array = np.arange(1,101)

In [5]:
arr =array.reshape(10,10)
print(arr)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


4.Using the previously defined matrix print rows 1,5,6

In [6]:
arr[[1,5,6]]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

5.Using the previously defined matrix print elemnts from 3rd row to 10th row

In [7]:
arr[3:]

array([[ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

6.Using the previously defined matrix print all elemtnts from 4th column to 8th column

In [8]:
arr[:,4:9]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49],
       [55, 56, 57, 58, 59],
       [65, 66, 67, 68, 69],
       [75, 76, 77, 78, 79],
       [85, 86, 87, 88, 89],
       [95, 96, 97, 98, 99]])

7.Using the same matrix print values from 3rd row 2nd coumn to 5th row 8th column 

In [9]:
arr[3:6,2:9]

array([[33, 34, 35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47, 48, 49],
       [53, 54, 55, 56, 57, 58, 59]])

8.Write a code to generate a 1000 random numbers each in the range(0,1) such that the count of all random points like are almost same .

In [10]:
np.random.randint(0,1,1000)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

9.Write the commands to get standard deviation, mean ,mode,median for a given vector

In [11]:
array = np.random.randint(0,50,10)

In [12]:
print(array)

[24  0 12 30 29  3 41  2 12  1]


In [13]:
np.mean(array)

15.4

In [14]:
np.median(array)

12.0

In [15]:
np.std(array)

13.88668426947196

In [17]:
from scipy import stats as st
mode = st.mode(array)
print(mode)

ModeResult(mode=array([12]), count=array([2]))
